solution: solution.cpp BaseHand.cpp Hand.cpp Hand2.cpp BaseHand.h Hand.h Hand2.h Classification.h
	g++ solution.cpp BaseHand.cpp Hand.cpp Hand2.cpp -g -o solution

.PHONY: clean
clean:
	rm solution BaseHand.o Hand.o Hand2.o
